git:
  depth: 3

language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"

before_install:
  - cpanm --quiet --notest AnyEvent::Twitter::Stream DBD::SQLite DBI File::Which Math::Round Moo Net::OAuth Net::Twitter::Lite::WithAPIv1_1 Statistics::Lite YAML::Tiny

install: true

script: true

notifications:
  email:
    on_success: never
    on_failure: change
